require 'mongoid/scroll/errors/base'
require 'mongoid/scroll/errors/multiple_sort_fields_error'
require 'mongoid/scroll/errors/different_sort_fields_error'
require 'mongoid/scroll/errors/invalid_cursor_error'
require 'mongoid/scroll/errors/no_such_field_error'
require 'mongoid/scroll/errors/unsupported_field_type_error'
